export const products = [
    {
        name: 'OG Shirt',
        pricing: 60.00,
        images: ['https://i.ibb.co/55z32tw/long-sleeve.png'],
        description: 'Product Description',
        category: 'Category',
        brand: 'Brand',
        countInStock: '10',
        rating: '5',
        numReviews: '10',
        createdAt: '2022-01-01T00:00:00.000Z',
        updatedAt: '2022-01-01T00:00:00.000Z',
        _id: '1',
        user: 'X',
        reviews: [],
        orders: [],
        orderItems: [],
        stock: 5,
        published: true
    },
    {
        name: 'OG Hoodie',
        pricing: 120.00,
        images: ['https://i.ibb.co/XzcwL5s/black-shearling.png'],
        description: 'Product Description',
        category: 'Category',
        brand: 'Brand',
        countInStock: '10',
        rating: '5',
        numReviews: '10',
        createdAt: '2022-01-01T00:00:00.000Z',
        updatedAt: '2022-01-01T00:00:00.000Z',
        _id: '2',
        user: 'X',
        reviews: [],
        orders: [],
        orderItems: [],
        stock: 5
    },
    {
        name: 'OG Sneakers',
        pricing: 150.00,
        images: ['https://i.ibb.co/bPmVXyP/black-converse.png'],
        description: 'Product Description',
        category: 'Category',
        brand: 'Brand',
        countInStock: '10',
        rating: '5',
        numReviews: '10',
        createdAt: '2022-01-01T00:00:00.000Z',
        updatedAt: '2022-01-01T00:00:00.000Z',
        _id: '3',
        user: 'X',
        reviews: [],
        orders: [],
        orderItems: [],
        stock: 5
        ,
        published: true
    },
    {
        name: 'OG Hat',
        pricing: 50.00,
        images: ['https://i.ibb.co/1f2nWMM/wolf-cap.png'],
        description: 'Product Description',
        category: 'Category',
        brand: 'Brand',
        countInStock: '10',
        rating: '5',
        numReviews: '10',
        createdAt: '2022-01-01T00:00:00.000Z',
        updatedAt: '2022-01-01T00:00:00.000Z',
        _id: '4',
        user: 'X',
        reviews: [],
        orders: [],
        orderItems: [],
        stock: 5
    },
    {
        name: 'OG Shirt 2',
        pricing: 60.00,
        images: ['https://i.ibb.co/mh3VM1f/polka-dot-shirt.png'],
        description: 'Product Description',
        category: 'Category',
        brand: 'Brand',
        countInStock: '10',
        rating: '5',
        numReviews: '10',
        createdAt: '2022-01-01T00:00:00.000Z',
        updatedAt: '2022-01-01T00:00:00.000Z',
        _id: '5',
        user: 'X',
        reviews: [],
        orders: [],
        orderItems: [],
        stock: 5,
        published: true
    },
]